import { useUser } from "@clerk/nextjs";
import Head from "next/head";
import { api } from "~/utils/api";

export default function SinglePostPage() {
  const { user, isLoaded: userLoaded, isSignedIn } = useUser();
  api.posts.getAll.useQuery();

  if (!userLoaded) return <div />;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div>SinglePostPage view</div>
      </main>
    </>
  );
}
